### ISSUE TITLE
Dumping broken in way too many ways

### ISSUE THREAD

**Issue by theAkito** [flyx/NimYAML#140]
So, I had the chance to thoroughly test NimYAML 2.0.0 dumping.
Unfortunately, this ended up in a disaster.

### Output of `canonicalDumper()` without any options whatsoever.

```
--- !<tag:nimyaml.org,2016:custom:ConfigMaster>
{
  ? !<tag:nimyaml.org,2016:field> "version"
  : !!str "appVersion",
  ? !<tag:nimyaml.org,2016:field> "contexts"
  : !<tag:nimyaml.org,2016:system:seq(tag:nimyaml.org;2016:custom:ConfigContext)> [
    !<tag:nimyaml.org,2016:custom:ConfigContext> {
      ? !<tag:nimyaml.org,2016:field> "dateFormat"
      : !!str "yyyy-MM-dd",
      ? !<tag:nimyaml.org,2016:field> "timeFormat"
      : !!str "HH:mm",
      ? !<tag:nimyaml.org,2016:field> "timeZone"
      : !!str "Europe/Oslo",
      ? !<tag:nimyaml.org,2016:field> "zoom"
      : !<tag:nimyaml.org,2016:custom:ConfigZoom> {
        ? !<tag:nimyaml.org,2016:field> "authentication"
        : !<tag:nimyaml.org,2016:system:seq(tag:nimyaml.org;2016:custom:ConfigZoomAuthentication)> [
          !<tag:nimyaml.org,2016:custom:ConfigZoomAuthentication> {
            ? !<tag:nimyaml.org,2016:field> "mail"
            : !!str "mail@example.com",
            ? !<tag:nimyaml.org,2016:field> "userID"
            : !!str "ZoomUserID",
            ? !<tag:nimyaml.org,2016:field> "accountID"
            : !!str "",
            ? !<tag:nimyaml.org,2016:field> "clientID"
            : !!str "",
            ? !<tag:nimyaml.org,2016:field> "clientSecret"
            : !!str ""
          }
        ],
        ? !<tag:nimyaml.org,2016:field> "patternKeywordsYes"
        : !<tag:nimyaml.org,2016:system:seq(tag:nimyaml.org;2016:custom:ConfigZoomPatternKeyword)> [
          !<tag:nimyaml.org,2016:custom:ConfigZoomPatternKeyword> {
            ? !<tag:nimyaml.org,2016:field> "statement"
            : !<tag:nimyaml.org,2016:custom:ConfigZoomFilterStatement> "OR",
            ? !<tag:nimyaml.org,2016:field> "keywords"
            : !<tag:nimyaml.org,2016:system:seq(tag:yaml.org;2002:str)> [
              !!str "MeetupTopicKeyword",
              !!str "Second Keyword",
              !!str "Juggernaut"
            ]
          }
        ],
        ? !<tag:nimyaml.org,2016:field> "patternKeywordsNo"
        : !<tag:nimyaml.org,2016:system:seq(tag:nimyaml.org;2016:custom:ConfigZoomPatternKeyword)> [
          !<tag:nimyaml.org,2016:custom:ConfigZoomPatternKeyword> {
            ? !<tag:nimyaml.org,2016:field> "statement"
            : !<tag:nimyaml.org,2016:custom:ConfigZoomFilterStatement> "AND",
            ? !<tag:nimyaml.org,2016:field> "keywords"
            : !<tag:nimyaml.org,2016:system:seq(tag:yaml.org;2002:str)> [
              !!str "NotAllowedKeyword",
              !!str "Nonsense",
              !!str "Test"
            ]
          }
        ]
      },
      ? !<tag:nimyaml.org,2016:field> "mail"
      : !<tag:nimyaml.org,2016:custom:ConfigPushMail> {
        ? !<tag:nimyaml.org,2016:field> "enable"
        : !!bool "false",
        ? !<tag:nimyaml.org,2016:field> "mailSender"
        : !<tag:nimyaml.org,2016:custom:ConfigMailSender> {
          ? !<tag:nimyaml.org,2016:field> "mail"
          : !!str "sender@example.com",
          ? !<tag:nimyaml.org,2016:field> "serverSMTP"
          : !!str "smtps.example.com",
          ? !<tag:nimyaml.org,2016:field> "portSMTP"
          : !<tag:nimyaml.org,2016:system:int64> "465",
          ? !<tag:nimyaml.org,2016:field> "user"
          : !!str "username",
          ? !<tag:nimyaml.org,2016:field> "password"
          : !!str "password",
          ? !<tag:nimyaml.org,2016:field> "startTLS"
          : !!bool "false"
        },
        ? !<tag:nimyaml.org,2016:field> "mailReceiver"
        : !<tag:nimyaml.org,2016:custom:ConfigMailReceiver> {
          ? !<tag:nimyaml.org,2016:field> "mails"
          : !<tag:nimyaml.org,2016:system:seq(tag:yaml.org;2002:str)> [
            !!str "friend1@example.com",
            !!str "friend2@example.com",
            !!str "friend3@example.com",
            !!str "friend4@example.com",
            !!str "friend5@example.com"
          ],
          ? !<tag:nimyaml.org,2016:field> "headerFrom"
          : !!str "Zoomer <zoomer@zoom.cf>",
          ? !<tag:nimyaml.org,2016:field> "subjectTpl"
          : !!str "Invitation to {zoom.TOPIC} on {zoom.START_DATE}",
          ? !<tag:nimyaml.org,2016:field> "bodyTpl"
          : !!str "You are invited to {zoom.TOPIC} at {zoom.START_TIME}!\n\nPlease, j\
            oin via the following link:\n\n{zoom.URL}\n\n\n\n\nThis E-Mail was \
            automatically generated and sent. Please do not reply."
        },
        ? !<tag:nimyaml.org,2016:field> "schedule"
        : !<tag:nimyaml.org,2016:system:seq(tag:nimyaml.org;2016:custom:ConfigPushSchedule)> [
          !<tag:nimyaml.org,2016:custom:ConfigPushSchedule> {
            ? !<tag:nimyaml.org,2016:field> "tType"
            : !<tag:nimyaml.org,2016:custom:ConfigPushScheduleTimeType> "DAYS",
            ? !<tag:nimyaml.org,2016:field> "amount"
            : !<tag:nimyaml.org,2016:system:int64> "7"
          },
          !<tag:nimyaml.org,2016:custom:ConfigPushSchedule> {
            ? !<tag:nimyaml.org,2016:field> "tType"
            : !<tag:nimyaml.org,2016:custom:ConfigPushScheduleTimeType> "DAYS",
            ? !<tag:nimyaml.org,2016:field> "amount"
            : !<tag:nimyaml.org,2016:system:int64> "3"
          },
          !<tag:nimyaml.org,2016:custom:ConfigPushSchedule> {
            ? !<tag:nimyaml.org,2016:field> "tType"
            : !<tag:nimyaml.org,2016:custom:ConfigPushScheduleTimeType> "HOURS",
            ? !<tag:nimyaml.org,2016:field> "amount"
            : !<tag:nimyaml.org,2016:system:int64> "1"
          },
          !<tag:nimyaml.org,2016:custom:ConfigPushSchedule> {
            ? !<tag:nimyaml.org,2016:field> "tType"
            : !<tag:nimyaml.org,2016:custom:ConfigPushScheduleTimeType> "MINUTES",
            ? !<tag:nimyaml.org,2016:field> "amount"
            : !<tag:nimyaml.org,2016:system:int64> "15"
          }
        ]
      }
    }
  ]
}
```

In all my trials, the following is the closest I could get to "working".

### Output of `minimalDumper()` with the following options.

```nim
import pkg/yaml

var dumper = minimalDumper()
# https://github.com/flyx/NimYAML/blob/854d33378e2b31ada7e54716439a4d6990460268/yaml/presenter.nim#L69-L80
dumper.presentation.containers = cBlock # Without it, broken output, too.
dumper.presentation.outputVersion = ovNone
dumper.presentation.newlines = nlLF
dumper.presentation.indentationStep = 1 # Have to set 1, to get an indentation of 2 spaces.
dumper.presentation.condenseFlow = false # Must be false to not break output.
dumper.presentation.suppressAttrs = false
dumper.presentation.directivesEnd = deNever
dumper.presentation.quoting = sqUnset # Supposed to be the default, but if unset by library user, everything is force quoted.
dumper.serialization.tagStyle = tsNone
dumper.serialization.handles = @[]
dumper.dump(config, fStream)
```

```yaml
# THIS first line is empty in output....
version: appVersion
contexts:
  -
    dateFormat: "yyyy-MM-dd"
    timeFormat: "HH:mm"
    timeZone: Europe/Oslo
    zoom:
      authentication:
        -
          mail: mail@example.com
          userID: ZoomUserID
          accountID: ""
          clientID: ""
          clientSecret: ""
      patternKeywordsYes:
        -
          statement: OR
          keywords:
            - MeetupTopicKeyword
            - Second Keyword
            - Juggernaut
      patternKeywordsNo:
        -
          statement: AND
          keywords:
            - NotAllowedKeyword
            - Nonsense
            - Test
    mail:
      enable: false
      mailSender:
        mail: sender@example.com
        serverSMTP: smtps.example.com
        portSMTP: 465
        user: username
        password: password
        startTLS: false
      mailReceiver:
        mails:
          - friend1@example.com
          - friend2@example.com
          - friend3@example.com
          - friend4@example.com
          - friend5@example.com
        headerFrom: Zoomer <zoomer@zoom.cf>
        subjectTpl: "Invitation to {zoom.TOPIC} on {zoom.START_DATE}"
        bodyTpl: |-
         You are invited to {zoom.TOPIC} at {zoom.START_TIME}!
         
         Please, join via the following link:
         
         {zoom.URL}
         
         
         
         
         This E-Mail was automatically generated and sent. Please do not reply.
      schedule:
        -
          tType: DAYS
          amount: 7
        -
          tType: DAYS
          amount: 3
        -
          tType: HOURS
          amount: 1
        -
          tType: MINUTES
          amount: 15

```

And now we are back to those additional newlines, which you already had fixed, though I cannot find the issue, we discussed it in, because I don't think it was https://github.com/flyx/NimYAML/issues/135 ...

# Hall of Fame

Without `dumper.presentation.quoting = sqUnset`.
```
"version": "appVersion"
"contexts":
    - "dateFormat": "yyyy-MM-dd"
        "timeFormat": "HH:mm"
        "timeZone": "Europe/Oslo"
        "zoom":
            "authentication":
                - "mail": "mail@example.com"
                    "userID": "ZoomUserID"
                    "accountID": ""
                    "clientID": ""
                    "clientSecret": ""
            "patternKeywordsYes":
                - "statement": "OR"
                    "keywords":
                        - "MeetupTopicKeyword"
                        - "Second Keyword"
                        - "Juggernaut"
            "patternKeywordsNo":
                - "statement": "AND"
                    "keywords":
                        - "NotAllowedKeyword"
                        - "Nonsense"
                        - "Test"
        "mail":
            "enable": "false"
            "mailSender":
                "mail": "sender@example.com"
                "serverSMTP": "smtps.example.com"
                "portSMTP": "465"
                "user": "username"
                "password": "password"
                "startTLS": "false"
            "mailReceiver":
                "mails":
                    - "friend1@example.com"
                    - "friend2@example.com"
                    - "friend3@example.com"
                    - "friend4@example.com"
                    - "friend5@example.com"
                "headerFrom": "Zoomer <zoomer@zoom.cf>"
                "subjectTpl": "Invitation to {zoom.TOPIC} on {zoom.START_DATE}"
                "bodyTpl": "You are invited to {zoom.TOPIC} at {zoom.START_TIME}!\n\nPlease, join via the following link:\n\n{zoom.URL}\n\n\n\n\nThis E-Mail was automatically generated and sent. Please do not reply."
            "schedule":
                - "tType": "DAYS"
                    "amount": "7"
                - "tType": "DAYS"
                    "amount": "3"
                - "tType": "HOURS"
                    "amount": "1"
                - "tType": "MINUTES"
                    "amount": "15"

```

?
```
? "version"
: "appVersion"
? "contexts"
: - ? "dateFormat"
        : "yyyy-MM-dd"
        ? "timeFormat"
        : "HH:mm"
        ? "timeZone"
        : "Europe/Oslo"
        ? "zoom"
        : ? "authentication"
            : - ? "mail"
                    : "mail@example.com"
                    ? "userID"
                    : "ZoomUserID"
                    ? "accountID"
                    : ""
                    ? "clientID"
                    : ""
                    ? "clientSecret"
                    : ""
            ? "patternKeywordsYes"
            : - ? "statement"
                    : "OR"
                    ? "keywords"
                    : - "MeetupTopicKeyword"
                        - "Second Keyword"
                        - "Juggernaut"
            ? "patternKeywordsNo"
            : - ? "statement"
                    : "AND"
                    ? "keywords"
                    : - "NotAllowedKeyword"
                        - "Nonsense"
                        - "Test"
        ? "mail"
        : ? "enable"
            : "false"
            ? "mailSender"
            : ? "mail"
                : "sender@example.com"
                ? "serverSMTP"
                : "smtps.example.com"
                ? "portSMTP"
                : "465"
                ? "user"
                : "username"
                ? "password"
                : "password"
                ? "startTLS"
                : "false"
            ? "mailReceiver"
            : ? "mails"
                : - "friend1@example.com"
                    - "friend2@example.com"
                    - "friend3@example.com"
                    - "friend4@example.com"
                    - "friend5@example.com"
                ? "headerFrom"
                : "Zoomer <zoomer@zoom.cf>"
                ? "subjectTpl"
                : "Invitation to {zoom.TOPIC} on {zoom.START_DATE}"
                ? "bodyTpl"
                : "You are invited to {zoom.TOPIC} at {zoom.START_TIME}!\n\nPle\
                  ase, join via the following link:\n\n{zoom.URL}\n\n\n\n\nThis\
                  \ E-Mail was automatically generated and sent. Please do not \
                  reply."
            ? "schedule"
            : - ? "tType"
                    : "DAYS"
                    ? "amount"
                    : "7"
                - ? "tType"
                    : "DAYS"
                    ? "amount"
                    : "3"
                - ? "tType"
                    : "HOURS"
                    ? "amount"
                    : "1"
                - ? "tType"
                    : "MINUTES"
                    ? "amount"
                    : "15"

```

Unquoted JSON.

```
{
 version: appVersion,
 contexts: [
  {
   dateFormat: "yyyy-MM-dd",
   timeFormat: "HH:mm",
   timeZone: Europe/Oslo,
   zoom: {
    authentication: [
     {
      mail: mail@example.com,
      userID: ZoomUserID,
      accountID: "",
      clientID: "",
      clientSecret: ""
     }
    ],
    patternKeywordsYes: [
     {
      statement: OR,
      keywords: [
       MeetupTopicKeyword,
       Second Keyword,
       Juggernaut
      ]
     }
    ],
    patternKeywordsNo: [
     {
      statement: AND,
      keywords: [
       NotAllowedKeyword,
       Nonsense,
       Test
      ]
     }
    ]
   },
   mail: {
    enable: false,
    mailSender: {
     mail: sender@example.com,
     serverSMTP: smtps.example.com,
     portSMTP: 465,
     user: username,
     password: password,
     startTLS: false
    },
    mailReceiver: {
     mails: [
      friend1@example.com,
      friend2@example.com,
      friend3@example.com,
      friend4@example.com,
      friend5@example.com
     ],
     headerFrom: Zoomer <zoomer@zoom.cf>,
     subjectTpl: "Invitation to {zoom.TOPIC} on {zoom.START_DATE}",
     bodyTpl: |-
      You are invited to {zoom.TOPIC} at {zoom.START_TIME}!
      
      Please, join via the following link:
      
      {zoom.URL}
      
      
      
      
      This E-Mail was automatically generated and sent. Please do not reply.
    },
    schedule: [
     {
      tType: DAYS,
      amount: 7
     },
     {
      tType: DAYS,
      amount: 3
     },
     {
      tType: HOURS,
      amount: 1
     },
     {
      tType: MINUTES,
      amount: 15
     }
    ]
   }
  }
 ]
}

```
