### ISSUE TITLE
Feature request: Field name annotation for loading

### ISSUE THREAD

**Issue by turbo** [flyx/NimYAML#146]
Serialized data I work with often has the correct structure, but rarely the desired naming. When loading YAML into Nim objects I'd like to be able to annotate or determine in another way, the key name the field should be loaded from.

For example:

```yaml
functions:
  - func: foo
    template: "foo($#)"
```

```nim
type
  FuncTemplate = object
    fn {.fromKey: "func".}: string
    tmpl {.fromKey: "template".}: string

  Config = object
    functions: seq[FuncTemplate]
```
