### ISSUE TITLE
Allow subtrees to be parsed into `YamlNode` when constructing native types to be able to carry over untyped information.

### ISSUE THREAD

**Issue by jaccarmac** [flyx/NimYAML#48]
I'd like to use NimYAML to parse a document which has some structure but is not totally specified. In general, it looks something like this.

```yaml
Name: parent
Children:
   - Name: child
     Children:
         - Name:
           Metadata:
               Key: value
               OtherKey: [arbitrary, value]
```

I can represent the nesting properly and even the fact that certain fields are optional. However, I run into problems deserializing `Metadata`. I can deal with string values, but in an idea world I would like to say the value can be any object. Is there a way to do this currently? I know I can approximate it with variants, but this means I need to update my codebase every time a new type of value is added. I've also run into #28 since I would prefer not to add tags to simple value types like `seq[string]`.
