### ISSUE TITLE
How to interpret/read associative lists of objects.

### ISSUE THREAD

**Issue by JohnAD** [flyx/NimYAML#81]
I'm converting the 70's-era game Colossal Cave Adventure to nim and have a YAML data file to parse. So, I'm building objects that should pull in the data. Unfortunately, I'm getting a run-time `Wrong tag for` message when doing the parsing. I've cut the YAML and code down to a few snippets to demonstrate:

The YAML:
```YAML
motions:
- MOT_2:
    words: ['road', 'hill']
- ENTER:
    words: ['enter']
- LOOK:
    words: ['l', 'x', 'look', 'exami', 'touch', 'descr']
    oldstyle: false
```

The code:
```nim
import tables
import yaml.serialization, streams

type
  Motion = object
    words: seq[string]
    oldstyle: bool
  World = object
    motions: OrderedTable[string, Motion]

var world*: World
var s = newFileStream("snippet.yaml")
load(s, world)
s.close()
```

The specific error seen:

```txt
Error: unhandled exception: Wrong tag for OrderedTable[system.string, small.Motion] [YamlConstructionError]
```

What is the best way to read and use the YAML file when it is structured this way?

BTW, I'm happy to fall back to this being a simple sequence of objects as long as I can get the keys (`MOT_2`, `ENTER`, etc.) inside those objects.

Also, slightly off-topic: Is there a way to get the run-time error to display the YAML source line that it stopped on?

I am running `yaml-0.13.1` with nim `1.2.0`.
